### ISSUE TITLE
Rule for "TrackName - 2003 Remastered"

### ISSUE THREAD

**Issue by keune** [web-scrobbler/metadata-filter#115]
I've recently come across a case which doesn't match any rule:

> Easy Living - 2003 Remastered

Some of Paul Desmond's older albums on Spotify are tagged this way. There might be other artists too.

There's a rule which matches "- 2003 Remaster", so maybe we could change the following rule;

```
// China Grove - 2006 Remaster
{ source: /-\s\d+(\s-)?\sRemaster$/, target: '' },
```

to:
`{ source: /-\s\d+(\s-)?\sRemaster(?:ed)?$/, target: '' },`

to cover both Remaster and Remastered. What do you think?

**Comment by alexesprit** [comment]
@keune This rule definitely should be updated to cover "Remastered" suffix as well. Feel free to open a PR with this change.

**Comment by keune** [comment]
#116
