### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by FOSSforlife** [web-scrobbler/metadata-filter#33]
Currently this module is unable to be used in a TypeScript project without using a custom type declaration file.

I've started [working on one](https://github.com/patricianapp/Harmonia/blob/develop/patches/metadata-filter%2B0.4.1.patch) for my project that I quickly generated using [dts-gen](https://github.com/microsoft/dts-gen) (and patched in using [patch-package](https://github.com/ds300/patch-package)), in which I updated the functions I needed to include correct types. It is far from complete at the moment.

I think the way to do this will be to write [d.ts files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) for each `.js` file in `src`, then use a [rollup plugin](https://github.com/wessberg/rollup-plugin-ts#declaration-files) to include this in the distributed bundle. I can take on this task, though it may take at least a couple weeks due to my work schedule.

**Comment by alexesprit** [comment]
a9d918f96728846fe9c00b4c676f852b8bcc1183 Don't that declaration modules work for you?

**Comment by FOSSforlife** [comment]
I don't think that's been published to npm yet. I don't see it when I run `npm install`. I'm on version 0.4.1.

**Comment by alexesprit** [comment]
You're right, it's not published. You can install the module from GitHub directly and check if declaration files work for you.

Note there're breaking changes in the master branch.

**Comment by FOSSforlife** [comment]
Okay I'm trying it out right now, and it almost works. It looks like because package.json has `filter.js` as the entry point, I can't import  any functions from the other files (e.g. `getYoutubeFilter()`).

**Comment by FOSSforlife** [comment]
I was able to get around this by using:

```typescript
import { getYoutubeFilter } from 'metadata-filter/dist/filters';
```

It might be good to have them all export from an `index.js` file (it seems like the types already do that, but not the .js files). I'll let you know if I run into any other issues.

**Comment by FOSSforlife** [comment]
Actually, the fix I mentioned above works in VSCode but not when I run the app using ts-node: `Error: Cannot find module 'metadata-filter/dist/filters'`

**Comment by FOSSforlife** [comment]
Actually never mind, I think I just needed to restart VSCode. It works now using the following:

```typescript
import { getYoutubeFilter, decodeHtmlEntities } from 'metadata-filter';
```

**Comment by alexesprit** [comment]
Yes, I extracted all static methods to the module scope.

This version has no ETA, so for now you can use either v0.4.1 with a custom definition file, or the one from the repository.

**Comment by alexesprit** [comment]
@FOSSforlife I rewrote the extension in TypeScript, so declaration files should be more accurate.

I noticed you use `metadata-filter` from the master branch directly, and changes I made could break something in your projects. Let me know if there're some issues related to declaration files.
