### ISSUE TITLE
Can I help to improve the filter?

### ISSUE THREAD

**Issue by peter9811** [web-scrobbler/metadata-filter#48]
My native language is Spanish and I would like to add some filters to make it more accurate

For example "live", "lyrics", "extended version", "audio" ... All these, but in Spanish.

Could you guide me a bit and help me improve also for Spanish?

![image](https://user-images.githubusercontent.com/22783445/91338679-4b770c00-e7a3-11ea-90d6-2b4a2df4a816.png)

**Comment by alexesprit** [comment]
Hi!

I'm rewriting the module in TypeScript right now, and will try to publish the changes shortly.

For now you can check how YouTube filter rules work:
- https://github.com/web-scrobbler/metadata-filter/blob/master/src/rules.js#L12
- https://github.com/web-scrobbler/metadata-filter/blob/master/src/functions.js#L69

**Comment by peter9811** [comment]
@alexesprit 
Hi!

I check a littler and try to do two simple rules to fix some problem. But badly I don't understand every the filters
Maybe with the TypeScript I would be understand more, and help doing perzonalized filter
