### ISSUE TITLE
"Weird Al" Yankovic parody filter

### ISSUE THREAD

**Issue by djmattyg007** [web-scrobbler/metadata-filter#81]
A large number of song titles on Spotify from "Weird Al" Yakovic are of the following form:

```
<SONG NAME> (Parody of "<ORIG SONG NAME>" by <ARTIST>)
```

For example: ``Canadian Idiot (Parody of "American Idiot" by Green Day)``

And possibly even the following:

```
<SONG NAME> (Parody of "<ORIG SONG NAME>" BY <ARTIST> feat. <FEATURED ARTIST>)
```

For example: ``White & Nerdy (Parody of "Ridin'" by Chamillionaire feat. Krayzie Bone)``

It would be nice to have an automatic filter for these kinds of song titles specifically for Weird Al, just because there are so many of them. Are artist-specific filters possible?

**Comment by djmattyg007** [comment]
I suppose I should clarify that I'd be looking to canonicalise the song names to entirely strip everything in the parentheses. So for example, this:

```
<SONG NAME> (Parody of "<ORIG SONG NAME>" by <ARTIST>)
Canadian Idiot (Parody of "American Idiot" by Green Day)
```

Should become this:

```
<SONG NAME>
Canadian Idiot
```

**Comment by alexesprit** [comment]
> Are artist-specific filters possible?

Sure, it's possible to do. But I think we can apply this filter to all tracks.

**Comment by djmattyg007** [comment]
:+1: I'll try to take a look at it over the weekend

**Comment by djmattyg007** [comment]
Just a few weeks late :P better late than never though
